# GET https://api.magicthegathering.io/v1/cards/555202/

# ### Users create (signup)
# POST http://localhost:3000/users.json
# Content-Type: application/json

# {
#   "name": "dan",
#   "email": "dan@dan.com",
#   "password": "password",
#   "password_confirmation": "password"
# }

GET http://localhost:3000/decks/1.json